/**
 * Print type event classes.
 *
 * Event classes for print operations that allow handlers to modify the generated output.
 *
 * @packageDocumentation
 */

import type {
  MDXString,
  Maybe,
  ComposePageTypeEventData,
  PageSection,
  PageSections,
  PrintCodeEventData,
  PrintTypeEventData,
} from "@graphql-markdown/types";

import type { CancellableEventOptions } from "@graphql-markdown/utils";

import { DataOutputEvent } from "@graphql-markdown/utils";

export type {
  ComposePageTypeEventData,
  PageSection,
  PageSections,
  PrintCodeEventData,
  PrintTypeEventData,
};

/**
 * Event emitted around code block generation for a GraphQL type.
 *
 * The `output` property is mutable, allowing event handlers to modify
 * the generated code before it's included in the documentation.
 *
 * @example
 * ```typescript
 * events.on(PrintTypeEvents.AFTER_PRINT_CODE, (event: PrintCodeEvent) => {
 *   // Add a comment to all generated code
 *   event.output = `# Auto-generated\n${event.output}`;
 * });
 * ```
 *
 * @category Events
 */
export class PrintCodeEvent extends DataOutputEvent<
  PrintCodeEventData,
  string
> {
  constructor(
    data: PrintCodeEventData,
    initialOutput: string,
    options?: CancellableEventOptions,
  ) {
    super(data, initialOutput, options);
  }
}

/**
 * Event emitted around full documentation generation for a GraphQL type.
 *
 * The `output` property is mutable, allowing event handlers to modify
 * the complete generated documentation.
 *
 * @example
 * ```typescript
 * events.on(PrintTypeEvents.AFTER_PRINT_TYPE, (event: PrintTypeEvent) => {
 *   // Add a footer to all type documentation
 *   event.output = `${event.output}\n\n---\nGenerated by GraphQL-Markdown`;
 * });
 * ```
 *
 * @category Events
 */
export class PrintTypeEvent extends DataOutputEvent<
  PrintTypeEventData,
  Maybe<MDXString>
> {
  constructor(
    data: PrintTypeEventData,
    initialOutput: Maybe<MDXString>,
    options?: CancellableEventOptions,
  ) {
    super(data, initialOutput, options);
  }
}

/**
 * Event emitted before composing page sections for a GraphQL type.
 *
 * This event fires after section content is generated and before sections are joined into final output.
 * The `output` property contains an array of section keys that will be included in the final page.
 * Handlers can reorder, filter, or append to this array to control the final page structure.
 *
 * @example
 * ```typescript
 * events.on(PrintTypeEvents.BEFORE_COMPOSE_PAGE_TYPE, (event: BeforeComposePageTypeEvent) => {
 *   // Move relations section before metadata
 *   const idx = event.output.indexOf('relations');
 *   if (idx > -1) {
 *     event.output.splice(idx, 1);
 *     const metaidx = event.output.indexOf('metadata');
 *     event.output.splice(metaidx, 0, 'relations');
 *   }
 * });
 * ```
 *
 * @category Events
 */
export class BeforeComposePageTypeEvent extends DataOutputEvent<
  ComposePageTypeEventData,
  (keyof PageSections)[]
> {
  constructor(
    data: ComposePageTypeEventData,
    initialOutput: (keyof PageSections)[],
    options?: CancellableEventOptions,
  ) {
    super(data, initialOutput, options);
  }
}
