/**
 * Print type event classes.
 *
 * Event classes for print operations that allow handlers to modify the generated output.
 *
 * @packageDocumentation
 */

import type {
  MDXString,
  Maybe,
  PrintTypeOptions,
} from "@graphql-markdown/types";

import { CancellableEvent, CancellableEventOptions } from "./base";

/**
 * Data payload for print code events.
 */
export interface PrintCodeEventData {
  /** The GraphQL type being printed */
  readonly type: unknown;
  /** The name of the type */
  readonly typeName: string;
  /** The print options in effect */
  readonly options: PrintTypeOptions;
}

/**
 * Event emitted before/after generating the code block for a GraphQL type.
 *
 * The `output` property is mutable, allowing event handlers to modify
 * the generated code before it's included in the documentation.
 *
 * @example
 * ```typescript
 * events.on(PrintTypeEvents.AFTER_PRINT_CODE, (event: PrintCodeEvent) => {
 *   // Add a comment to all generated code
 *   event.output = `# Auto-generated\n${event.output}`;
 * });
 * ```
 *
 * @category Events
 */
export class PrintCodeEvent extends CancellableEvent {
  /** Read-only event data */
  readonly data: PrintCodeEventData;

  /**
   * The generated code output.
   * Handlers can modify this property to change the final output.
   */
  output: string;

  constructor(
    data: PrintCodeEventData,
    initialOutput: string,
    options?: CancellableEventOptions,
  ) {
    super(options);
    this.data = data;
    this.output = initialOutput;
  }
}

/**
 * Data payload for print type events.
 */
export interface PrintTypeEventData {
  /** The GraphQL type being printed */
  readonly type: unknown;
  /** The name identifier for the type */
  readonly name: Maybe<string>;
  /** The print options in effect */
  readonly options: PrintTypeOptions;
}

/**
 * Event emitted before/after generating the full documentation for a GraphQL type.
 *
 * The `output` property is mutable, allowing event handlers to modify
 * the complete generated documentation.
 *
 * @example
 * ```typescript
 * events.on(PrintTypeEvents.AFTER_PRINT_TYPE, (event: PrintTypeEvent) => {
 *   // Add a footer to all type documentation
 *   event.output = `${event.output}\n\n---\nGenerated by GraphQL-Markdown`;
 * });
 * ```
 *
 * @category Events
 */
export class PrintTypeEvent extends CancellableEvent {
  /** Read-only event data */
  readonly data: PrintTypeEventData;

  /**
   * The generated documentation output.
   * Handlers can modify this property to change the final output.
   */
  output: Maybe<MDXString>;

  constructor(
    data: PrintTypeEventData,
    initialOutput: Maybe<MDXString>,
    options?: CancellableEventOptions,
  ) {
    super(options);
    this.data = data;
    this.output = initialOutput;
  }
}
