VERSION 0.8

IMPORT .. AS root

ARG --global docusaurusVersion="latest"
ARG --global docusaurusProject="docusaurus-gqlmd"

build-docusaurus-examples:
  FROM root+build-docusaurus-project
  WORKDIR /$docusaurusProject
  RUN --mount=type=cache,target=/root/.npm npm install --save prettier
  RUN npm install --save ./graphql-markdown-cli.tgz ./graphql-markdown-docusaurus.tgz
  DO +BUILD_EXAMPLES
  SAVE ARTIFACT ./examples

build-cli-examples:
  FROM root+setup-cli-project
  WORKDIR /$gqlmdCliProject
  RUN --mount=type=cache,target=/root/.npm npm install --save prettier
  RUN npm install --save ./graphql-markdown-cli.tgz
  COPY root+assets/data/graphql.config.mjs ./graphql.config.mjs
  DO +BUILD_EXAMPLES --command=gqlmd
  SAVE ARTIFACT ./examples

build-api-docs:
  FROM root+build
  COPY root+assets/docs/__api/__index.md /graphql-markdown/docs/__api/__index.md
  RUN bun run docs:api
  SAVE ARTIFACT ./api

build-docs:
  FROM root+alpine
  COPY --dir ./src ./src
  COPY --dir ./static ./static
  COPY package.json package-lock.json docusaurus.config.js llms.config.js ./
  COPY +build-docusaurus-examples/examples ./examples
  COPY +build-api-docs/api ./api
  COPY root+assets/docs ./docs
  RUN --mount=type=cache,target=/root/.npm npm ci
  RUN --mount=type=cache,target=/root/.npm npx update-browserslist-db@latest
  RUN NODE_OPTIONS="--max-old-space-size=4096" DOCUSAURUS_IGNORE_SSG_WARNINGS=true npm run build
  SAVE ARTIFACT --force ./build AS LOCAL build

build-image:
  FROM +build-docs
  EXPOSE 8080
  ENTRYPOINT ["npm", "run", "serve", "--",  "--host=0.0.0.0", "--port=8080"]
  SAVE IMAGE graphql-markdown:docs

# --- UDCs (localized to website) ---

BUILD_EXAMPLES:
  FUNCTION
  ARG command=docusaurus
  LET folderDocs="examples"
  LET folderExample="default"
  LET idExample="default"
  DO root+INSTALL_GRAPHQL
  DO root+INSTALL_GQLMD
  RUN mkdir $folderDocs
  DO root+GQLMD --command=$command --options="--homepage data/anilist.md --schema https://graphql.anilist.co/ --base . --link /${folderDocs}/${folderExample} --force --pretty --deprecated group"
  RUN mv docs ./$folderDocs/$folderExample
  SET folderExample="group-by"
  SET idExample="schema_with_grouping"
  DO root+GQLMD --command=$command --id="${idExample}" --options="--homepage data/groups.md --schema data/${idExample}.graphql --groupByDirective @doc(category|=Common) --base . --link /${folderDocs}/${folderExample} --skip @noDoc --index --noParentType --noRelatedType --deprecated group --hierarchy entity"
  RUN mv docs ./$folderDocs/$folderExample
  SAVE ARTIFACT ./$folderDocs
