name: Auto approve & merge PR

on: pull_request_target

env:
  PR_URL: ${{ github.event.pull_request.html_url }}

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]' || 
      github.actor == 'dependabot-preview[bot]' || 
      github.actor == 'renovate[bot]' || 
      github.actor == 'graphql-markdown-bot'
    env:
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
    steps:
      - name: Auto approve
        run: gh pr review --approve "$PR_URL"
      - name: Add label "automerge"
        run: gh pr edit --add-label "automerge" "$PR_URL"
        
  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: | 
      github.repository == 'graphql-markdown/graphql-markdown'
    env:
      GH_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
    steps:
      - name: Auto merge
        run: gh pr merge --auto --squash "$PR_URL"
