name: Changelog
run-name: ${{ format('Changelog release {0}', github.event.release.name) }}

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: update-changelog
  cancel-in-progress: false

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: main
          token: ${{ secrets.BOT_PAT }}

      - uses: rhysd/changelog-from-release/action@78b335bb7d059f35ad04c5428d50711726feee50 # v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.BOT_PAT }}
          commit_summary_template: "update changelog for %s changes"
          pull_request: true
